# Configuration for the V2 Reconnaissance Phase

# Paths to tools
# If the tool is in the system's PATH, you can just use the tool name.
# Otherwise, provide the full path.
tools:
  gobuster: bin/gobuster
  massdns: bin/massdns # Not implemented yet
  puredns: bin/puredns
  dnsgen: bin/dnsgen # Not implemented yet
  gotator: bin/gotator # Not implemented yet
  linkfinder: bin/linkfinder # Not implemented yet
  gowitness: bin/gowitness
  aquatone: bin/aquatone
  wappalyzer: bin/wappalyzer # Not implemented yet
  naabu: bin/naabu # Not implemented yet
  nmap: bin/nmap
  httpx: bin/httpx
  subfinder: bin/subfinder
  amass: bin/amass
  assetfinder: bin/assetfinder
  subzy: bin/subzy # Not implemented yet
  nuclei: bin/nuclei
  goblob: bin/goblob
  s3scanner: bin/s3scanner
  dnsx: bin/dnsx # Not implemented yet
  gospider: bin/gospider # Not implemented yet
  gau: bin/gau # Not implemented yet
  sublist3r: bin/sublist3r # Not implemented yet
  gh_dork: bin/gh_dork # Not implemented yet

# Paths to wordlists
wordlists:
  dns_bruteforce: /usr/share/seclists/Discovery/DNS/subdomains-top1million-5000.txt
  resolvers: /usr/share/seclists/Discovery/DNS/resolvers.txt
  github_dorks: gh-dork/dorks.txt

# Other settings
recon_output_dir: recon_results
screenshot_dir: screenshots
nmap_output_dir: nmap
final_recon_file: final_recon_data.json
master_subdomains_file: master_subdomains.txt
